openapi: 3.0.4
info:
  title: Acartia API
  version: 1.0

servers:
  - url: /api/v1

paths:
  /auth/login:
    $ref: "./requests/login.yml"
  /auth/register:
    $ref: "./requests/register.yml"
  /sightings:
    $ref: "./requests/sightings.yml"
  /profile:
    $ref: "./requests/profile.yml"
