/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in */
        post: operations["signIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sightings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get sightings */
        get: operations["getSightings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        role: "admin" | "user";
        user: {
            id: string;
            name: string;
            role: components["schemas"]["role"];
            isApproved: boolean;
            email: string;
            /** Format: date-time */
            createdAt: string;
        };
        "auth-response": {
            token: string;
            user: components["schemas"]["user"];
        };
        sighting: {
            ssemmi_id: string;
            data_source_name: string;
            data_source_entity: string;
            data_source_id: number;
            /** Format: date-time */
            created: string;
            photo_url?: string;
            no_sighted: number;
            latitude: number;
            longitude: number;
            type: string;
            data_source_witness: string;
            trusted: boolean;
            data_source_comments?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    signIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    access_token?: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["auth-response"];
                };
            };
        };
    };
    getSightings: {
        parameters: {
            query?: {
                startDate?: string;
                endDate?: string;
                species?: string[];
                contributors?: string[];
                trusted?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["sighting"][];
                };
            };
        };
    };
}
