spring:
  application:
    name: acartia
  datasource:
    url: jdbc:tc:postgresql:15.5:///acartia
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  jackson:
    # For future reference: https://fasterxml.github.io/jackson-annotations/javadoc/2.7/com/fasterxml/jackson/annotation/JsonInclude.Include.html
    default-property-inclusion: non_absent

logging:
  level:
    root: INFO

server:
  servlet:
    context-path: /api/v1
  tomcat:
    accesslog:
      enabled: true
      directory: /dev
      prefix: stdout
      suffix: ""
      file-date-format: ""
      pattern: common
      rotate: false

acartia:
  legacy:
    base-url: https://acartia.io/api/v1
